const pages = {
  home:{title:'Manual de Conduta',group:'INTRODUÇÃO',icon:'▤',eyebrow:'Documento Oficial',lead:'O 1º Batalhão de Polícia Militar Hardline estabelece, através deste manual, normas, critérios e princípios que regem a conduta, organização e funcionamento da corporação.',html:`
    <div class="callout"><div class="ico">ⓘ</div><div>Este manual define os limites de atuação do policial. O agente público deve conhecer, respeitar e aplicar os procedimentos estabelecidos pela corporação.</div></div>
    <h2>Sobre este Manual</h2><p>O presente manual busca preservar os princípios de disciplina, integridade, profissionalismo e respeito. Seu conteúdo serve como referência para a atuação cotidiana dos integrantes do 1º BPM HARDLINE.</p>
    <div class="callout warn"><div class="ico">⚠</div><div>As normas aqui descritas devem ser observadas em conjunto com as determinações do comando e demais regulamentos oficiais vigentes.</div></div>
    <h2>Acesso rápido</h2><div class="cards"><div class="card" data-go="hierarquia"><div class="card-icon">🎖️</div><strong>Hierarquia Militar</strong><span>Consulte patentes, precedência e estrutura do batalhão.</span></div><div class="card" data-go="comunicacao"><div class="card-icon">📡</div><strong>Comunicação</strong><span>Rádio, códigos Q e padrões de comunicação operacional.</span></div><div class="card" data-go="abordagem"><div class="card-icon">🤝</div><strong>Abordagem</strong><span>Princípios e etapas para uma abordagem organizada.</span></div></div>`},
  regulamento:{title:'Regulamento Básico',group:'INTRODUÇÃO',icon:'▤',eyebrow:'Normas Fundamentais',lead:'Diretrizes gerais que orientam a permanência, atuação e responsabilidade dos integrantes do 1º BPM HARDLINE.',html:`<div class="callout"><div class="ico">ⓘ</div><div>O regulamento básico é a referência inicial de qualquer integrante da corporação e deve ser conhecido antes do início das atividades operacionais.</div></div><h2>Princípios fundamentais</h2><div class="steps"><div class="step"><div><h3>Disciplina</h3><p>Ordens legítimas devem ser cumpridas dentro da cadeia de comando e dos procedimentos estabelecidos.</p></div></div><div class="step"><div><h3>Respeito</h3><p>O tratamento com civis, colegas e superiores deve permanecer profissional e compatível com a função pública.</p></div></div><div class="step"><div><h3>Responsabilidade</h3><p>Cada agente responde por suas decisões, registros e condutas durante o serviço.</p></div></div></div>`},
  hierarquia:{title:'Hierarquia Militar',group:'ORGANIZAÇÃO',icon:'🎖️',eyebrow:'Organização',lead:'Estrutura hierárquica de referência para identificação de funções e cadeia de comando.',html:`<div class="stat-grid"><div class="stat"><b>01</b><span>Comando</span></div><div class="stat"><b>02</b><span>Oficiais</span></div><div class="stat"><b>03</b><span>Graduados</span></div><div class="stat"><b>04</b><span>Praças</span></div></div><h2>Patentes</h2><div class="table-wrap"><table><thead><tr><th>Patente</th><th>Categoria</th><th>Função de referência</th></tr></thead><tbody><tr><td><span class="badge blue">CEL</span></td><td>Comando</td><td>Comando geral</td></tr><tr><td><span class="badge blue">CAP</span></td><td>Oficial</td><td>Supervisão e comando</td></tr><tr><td><span class="badge blue">TEN</span></td><td>Oficial</td><td>Coordenação operacional</td></tr><tr><td><span class="badge blue">SGT</span></td><td>Graduado</td><td>Liderança de equipe</td></tr><tr><td><span class="badge blue">CB</span></td><td>Praça</td><td>Apoio operacional</td></tr><tr><td><span class="badge blue">SD</span></td><td>Praça</td><td>Atuação operacional</td></tr><tr><td><span class="badge blue">ALUNO</span></td><td>Formação</td><td>Período de instrução</td></tr></tbody></table></div>`},
  upf:{title:'Conduta Militar (UPF)',group:'ORGANIZAÇÃO',icon:'⚡',eyebrow:'Disciplina',lead:'Padrões de conduta e postura profissional esperados durante o serviço.',html:`<h2>Postura profissional</h2><p>O policial deve manter postura compatível com a função, preservar a cadeia de comando e evitar atitudes que comprometam a confiança na instituição.</p><div class="callout success"><div class="ico">✓</div><div>Priorize comunicação clara, cumprimento de procedimentos, registro adequado das ocorrências e respeito entre integrantes.</div></div><h2>Responsabilidade</h2><p>Condutas incompatíveis com o regulamento poderão ser avaliadas pela cadeia de comando conforme a natureza da ocorrência e as normas vigentes.</p>`},
  comunicacao:{title:'Comunicação',group:'OPERAÇÕES',icon:'📡',eyebrow:'Operações',lead:'Padrão de comunicação para manter o rádio objetivo, organizado e compreensível.',html:`<h2>Regras de rádio</h2><div class="cards"><div class="card"><div class="card-icon">🎙️</div><strong>Objetividade</strong><span>Transmita somente o necessário para a operação.</span></div><div class="card"><div class="card-icon">📍</div><strong>Localização</strong><span>Informe QTH ou referência clara quando necessário.</span></div><div class="card"><div class="card-icon">🚨</div><strong>Prioridade</strong><span>Chamados urgentes devem ter prioridade sobre comunicações secundárias.</span></div></div>`},
  codigos:{title:'Códigos Q',group:'OPERAÇÕES',icon:'▣',eyebrow:'Comunicação Operacional',lead:'Referência rápida para códigos utilizados na comunicação da corporação.',html:`<div class="q-grid"><div class="q"><b>QAP</b><span>Na escuta / disponível.</span></div><div class="q"><b>QSL</b><span>Entendido / confirmado.</span></div><div class="q"><b>QTH</b><span>Localização.</span></div><div class="q"><b>QRR</b><span>Apoio imediato.</span></div><div class="q"><b>QRA</b><span>Identificação / nome.</span></div><div class="q"><b>QRT</b><span>Encerrar transmissão.</span></div></div><div class="callout warn"><div class="ico">⚠</div><div>Os códigos devem ser usados de forma objetiva e sem ocupar o canal durante situações de alta prioridade.</div></div>`},
  acompanhamento:{title:'Acompanhamento',group:'OPERAÇÕES',icon:'🚓',eyebrow:'Procedimento Operacional',lead:'Orientações gerais para acompanhamento veicular dentro dos protocolos do batalhão.',html:`<h2>Antes de iniciar</h2><div class="steps"><div class="step"><div><h3>Comunicar</h3><p>Informe a situação pelo rádio e identifique a viatura envolvida.</p></div></div><div class="step"><div><h3>Avaliar</h3><p>Considere tráfego, risco, local e necessidade de apoio.</p></div></div><div class="step"><div><h3>Coordenar</h3><p>Utilize comunicações curtas e mantenha as demais unidades informadas.</p></div></div></div>`},
  revista:{title:'Revista',group:'OPERAÇÕES',icon:'🔎',eyebrow:'Procedimento Operacional',lead:'Procedimentos de segurança e organização para revistas realizadas durante ocorrências.',html:`<div class="callout"><div class="ico">ⓘ</div><div>Realize procedimentos de forma proporcional à situação, mantendo comunicação clara e priorizando a segurança de todos os envolvidos.</div></div><h2>Boas práticas</h2><p>Identifique a situação, mantenha atenção ao ambiente, comunique sua ação e registre informações relevantes da ocorrência.</p>`},
  abordagem:{title:'Abordagem',group:'OPERAÇÕES',icon:'🤝',eyebrow:'Procedimento Operacional',lead:'Fluxo de referência para abordagens organizadas e profissionais.',html:`<div class="steps"><div class="step"><div><h3>Identificação</h3><p>Apresente-se e estabeleça uma comunicação objetiva.</p></div></div><div class="step"><div><h3>Motivo</h3><p>Informe de forma clara o motivo da abordagem quando cabível.</p></div></div><div class="step"><div><h3>Verificação</h3><p>Faça as verificações necessárias seguindo os procedimentos internos.</p></div></div><div class="step"><div><h3>Encerramento</h3><p>Finalize a abordagem de maneira clara e registre a ocorrência quando necessário.</p></div></div></div>`},
  cod5:{title:'Comportamento em CÓD.5',group:'OPERAÇÕES',icon:'🔴',eyebrow:'Código de Conduta',lead:'Referência para situações classificadas como CÓD.5.',html:`<div class="callout warn"><div class="ico">⚠</div><div>Em situações críticas, mantenha comunicação objetiva, siga a cadeia de comando e priorize a segurança da operação.</div></div><h2>Procedimento</h2><p>Acione apoio quando necessário, mantenha o canal organizado e siga as instruções do comando responsável pela ocorrência.</p>`},
  infracoes:{title:'Infrações e Definições',group:'INFRAÇÕES',icon:'⚖️',eyebrow:'Disciplina',lead:'Classificação e referência para análise de condutas incompatíveis com as normas internas.',html:`<div class="table-wrap"><table><thead><tr><th>Classificação</th><th>Descrição</th><th>Tratamento</th></tr></thead><tbody><tr><td><span class="badge red">LEVE</span></td><td>Descumprimento pontual sem impacto operacional relevante.</td><td>Orientação / medida disciplinar cabível.</td></tr><tr><td><span class="badge red">MÉDIA</span></td><td>Conduta que prejudica procedimento ou disciplina.</td><td>Avaliação pelo comando.</td></tr><tr><td><span class="badge red">GRAVE</span></td><td>Conduta de elevado impacto institucional ou operacional.</td><td>Processo conforme regulamento.</td></tr></tbody></table></div>`},
  cursoCom:{title:'Comunicação Operacional',group:'CURSOS',icon:'📡',eyebrow:'Curso',lead:'Módulo de treinamento para padronização da comunicação em serviço.',html:`<h2>Objetivo</h2><p>Capacitar o policial a transmitir informações com clareza, brevidade e prioridade adequada.</p><div class="cards"><div class="card"><strong>Rádio</strong><span>Disciplina e organização do canal.</span></div><div class="card"><strong>Códigos Q</strong><span>Uso correto das abreviações.</span></div><div class="card"><strong>Prioridade</strong><span>Gerenciamento de chamadas.</span></div></div>`},
  modulacao:{title:'Modulação e Anúncios',group:'CURSOS',icon:'🎙️',eyebrow:'Curso',lead:'Padrão de voz e estrutura para anúncios operacionais.',html:`<h2>Estrutura recomendada</h2><div class="steps"><div class="step"><div><h3>Identificação</h3><p>Informe sua unidade ou identificação operacional.</p></div></div><div class="step"><div><h3>Local</h3><p>Informe onde a situação está ocorrendo.</p></div></div><div class="step"><div><h3>Solicitação</h3><p>Diga objetivamente o que precisa ser feito.</p></div></div></div>`},
  tablet:{title:'Curso de Tablet',group:'CURSOS',icon:'📱',eyebrow:'Curso',lead:'Uso operacional do tablet e organização das informações.',html:`<h2>Boas práticas</h2><p>Mantenha os registros atualizados, confira informações antes de agir e utilize os recursos do sistema de acordo com os procedimentos internos.</p>`},
  cursoAcomp:{title:'Curso de Acompanhamento',group:'CURSOS',icon:'🚓',eyebrow:'Curso',lead:'Treinamento sobre coordenação e comunicação durante acompanhamentos.',html:`<div class="callout"><div class="ico">ⓘ</div><div>O treinamento deve priorizar coordenação entre viaturas, comunicação e avaliação contínua do risco.</div></div>`},
  boosting:{title:'Boosting',group:'CURSOS',icon:'🚘',eyebrow:'Curso',lead:'Módulo específico para procedimentos relacionados a operações de boosting.',html:`<p>Área reservada para o conteúdo oficial do curso, critérios de habilitação e procedimentos internos.</p>`},
  ruas:{title:'Ruas e Referências',group:'CURSOS',icon:'🗺️',eyebrow:'Referência',lead:'Material de apoio para localização e comunicação de pontos de referência.',html:`<p>Adicione aqui o mapa operacional, nomenclatura de regiões e referências utilizadas pelo 1º BPM HARDLINE.</p>`},
  cursoAb:{title:'Curso de Abordagem',group:'CURSOS',icon:'🤝',eyebrow:'Curso',lead:'Treinamento para execução padronizada de abordagens.',html:`<h2>Conteúdo</h2><div class="cards"><div class="card"><strong>Preparação</strong><span>Avaliação da situação e posicionamento.</span></div><div class="card"><strong>Contato</strong><span>Comunicação e controle da ocorrência.</span></div><div class="card"><strong>Finalização</strong><span>Encerramento e registro.</span></div></div>`}
};

const navGroups=[
 ['INTRODUÇÃO',[['home','Manual de Conduta','▤'],['regulamento','Regulamento Básico','▤']]],
 ['ORGANIZAÇÃO',[['hierarquia','Hierarquia Militar','🎖️'],['upf','Conduta Militar (UPF)','⚡']]],
 ['OPERAÇÕES',[['comunicacao','Comunicação','📡'],['codigos','Códigos Q','▣'],['acompanhamento','Acompanhamento','🚓'],['revista','Revista','🔎'],['abordagem','Abordagem','🤝'],['cod5','Comportamento em CÓD.5','🔴']]],
 ['INFRAÇÕES',[['infracoes','Infrações e Definições','⚖️']]],
 ['CURSOS',[['cursoCom','Comunicação Operacional','📡'],['modulacao','Modulação e Anúncios','🎙️'],['tablet','Curso de Tablet','📱'],['cursoAcomp','Curso de Acompanhamento','🚓'],['boosting','Boosting','🚘'],['ruas','Ruas e Referências','🗺️'],['cursoAb','Curso de Abordagem','🤝']]]
];
const nav=document.getElementById('nav');
nav.innerHTML=navGroups.map(([g,items])=>`<div class="nav-group"><div class="nav-title">${g}</div>${items.map(([id,label,icon])=>`<div class="nav-item" data-go="${id}"><span class="nav-icon">${icon}</span><span>${label}</span></div>`).join('')}</div>`).join('');

let current='home';
function render(id, push=true){const p=pages[id]||pages.home;current=id;document.title=`1º BPM HARDLINE — ${p.title}`;document.getElementById('crumb').textContent=p.title;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.go===id));
 const ids=Object.keys(pages),i=ids.indexOf(id),prev=ids[(i-1+ids.length)%ids.length],next=ids[(i+1)%ids.length];
 document.getElementById('content').innerHTML=`<div class="eyebrow ${p.eyebrow==='Documento Oficial'?'':'blue'}">${p.icon} &nbsp; ${p.eyebrow}</div><h1>${p.title}</h1><p class="lead">${p.lead}</p><div class="rule"></div>${p.html}<div class="pager"><button data-go="${prev}">← Anterior</button><button data-go="${next}">Próximo →</button></div>`;
 if(push) history.pushState({id},'',`#${id}`);window.scrollTo({top:0,behavior:'smooth'});document.getElementById('sidebar').classList.remove('open');
}

document.addEventListener('click',e=>{const el=e.target.closest('[data-go]');if(el)render(el.dataset.go);});
window.addEventListener('popstate',()=>render(location.hash.slice(1)||'home',false));
const initial=location.hash.slice(1);render(pages[initial]?initial:'home',false);

document.getElementById('mobileMenu').onclick=()=>document.getElementById('sidebar').classList.toggle('open');
const modal=document.getElementById('searchModal'), input=document.getElementById('modalSearch'), results=document.getElementById('results');
function openSearch(){modal.classList.remove('hidden');input.value=document.getElementById('searchInput').value;input.focus();doSearch();}
function doSearch(){const q=input.value.toLowerCase().trim();if(!q){results.innerHTML='<div class="no-results">Digite um termo para pesquisar.</div>';return}const found=Object.entries(pages).filter(([id,p])=>(p.title+' '+p.group+' '+p.lead+' '+p.html.replace(/<[^>]+>/g,' ')).toLowerCase().includes(q));results.innerHTML=found.length?found.map(([id,p])=>`<div class="result" data-go="${id}"><b>${p.title}</b><span>${p.group} · ${p.lead.slice(0,100)}...</span></div>`).join(''):'<div class="no-results">Nenhum resultado encontrado.</div>';}
document.getElementById('searchInput').addEventListener('focus',openSearch);document.getElementById('searchInput').addEventListener('keydown',e=>{if(e.key==='Enter')openSearch()});input.addEventListener('input',doSearch);document.getElementById('closeSearch').onclick=()=>modal.classList.add('hidden');modal.addEventListener('click',e=>{if(e.target===modal)modal.classList.add('hidden')});document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();openSearch()}if(e.key==='Escape')modal.classList.add('hidden')});
